version: 2
orbs:
  android: circleci/android@1.0.3
  flutter-orb: tadashi0713/flutter-orb@1.2.0
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.10.1
          app-dir: ./app
      - run: echo "Clean"
      - run: flutter doctor
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release
