# This file defines a workflow that analyzes your codebase and intelligently creates a
# new configuration file with build/test/deploy jobs that are specific to your setup
version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  build-android:
    executor: android
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.7.5
      - run:
          name: Build APK
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/

workflows:
  analyze-my-code:
    jobs:
      - build-android

