jobs:
  build-android:
    executor: android
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.7.5
      - run:
          name: Build APK
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/

  tests:
    executor: android
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 3.7.5
      - run:
          name: Run unit test
          command: flutter test

orbs:
  flutter-orb: circleci/flutter@1.1.0

version: 2.1

workflows:
  main:
    jobs:
      - tests
      - build-android:
          requires:
            - tests
      - build-ios:
          requires:
            - tests
